// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vadnrbkqrukvzjsuglpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZG5yYmtxcnVrdnpqc3VnbHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNzM0MzcsImV4cCI6MjA3Mzc0OTQzN30.i3514k6MkzBtkHIVsOh6rFfUwowg6wkDcqhfwKTgsQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});